### ISSUE TITLE
Installation errors in newest version

### ISSUE THREAD

**Issue by dirkjordan** [NREL/rdtools#54]
When i try to install from the pip install rdtools, or a local download version, installation fails.  
Error message:

> C:\Users\djordan\Downloads\rdtools-master\rdtools-master>pip install .
Processing c:\users\djordan\downloads\rdtools-master\rdtools-master
Requirement already satisfied: numpy>=1.11.2 in c:\users\djordan\anaconda2\lib\s
ite-packages (from rdtools==1.1.2)
Requirement already satisfied: pandas>=0.20.3 in c:\users\djordan\anaconda2\lib\
site-packages (from rdtools==1.1.2)
Requirement already satisfied: pvlib>=0.5.0 in c:\users\djordan\anaconda2\lib\si
te-packages (from rdtools==1.1.2)
Requirement already satisfied: statsmodels>=0.8.0 in c:\users\djordan\anaconda2\
lib\site-packages (from rdtools==1.1.2)
Requirement already satisfied: scipy>=0.19.1 in c:\users\djordan\anaconda2\lib\s
ite-packages (from rdtools==1.1.2)
Requirement already satisfied: patsy>=0.4.1 in c:\users\djordan\anaconda2\lib\si
te-packages (from rdtools==1.1.2)
Requirement already satisfied: h5py>=2.7.1 in c:\users\djordan\anaconda2\lib\sit
e-packages (from rdtools==1.1.2)
Requirement already satisfied: pytz in c:\users\djordan\anaconda2\lib\site-packa
ges (from rdtools==1.1.2)
Requirement already satisfied: six in c:\users\djordan\anaconda2\lib\site-packag
es (from rdtools==1.1.2)
Requirement already satisfied: python-dateutil in c:\users\djordan\anaconda2\lib
\site-packages (from pandas>=0.20.3->rdtools==1.1.2)
Building wheels for collected packages: rdtools
  Running setup.py bdist_wheel for rdtools ... error
  Complete output from command C:\Users\djordan\Anaconda2\python.exe -u -c "impo
rt setuptools, tokenize;__file__='c:\\users\\djordan\\appdata\\local\\temp\\1\\p
ip-rppf0k-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.re
ad().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdis
t_wheel -d c:\users\djordan\appdata\local\temp\1\tmpoywwgupip-wheel- --python-ta
g cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\rdtools
  copying rdtools\aggregation.py -> build\lib\rdtools
  copying rdtools\clearsky_temperature.py -> build\lib\rdtools
  copying rdtools\degradation.py -> build\lib\rdtools
  copying rdtools\filtering.py -> build\lib\rdtools
  copying rdtools\normalization.py -> build\lib\rdtools
  copying rdtools\_version.py -> build\lib\rdtools
  copying rdtools\__init__.py -> build\lib\rdtools
  running egg_info
  creating rdtools.egg-info
  writing requirements to rdtools.egg-info\requires.txt
  writing rdtools.egg-info\PKG-INFO
  writing top-level names to rdtools.egg-info\top_level.txt
  writing dependency_links to rdtools.egg-info\dependency_links.txt
  writing manifest file 'rdtools.egg-info\SOURCES.txt'
  reading manifest file 'rdtools.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'rdtools.egg-info\SOURCES.txt'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "c:\users\djordan\appdata\local\temp\1\pip-rppf0k-build\setup.py", line
 88, in <module>
      **setuptools_kwargs)
    File "C:\Users\djordan\Anaconda2\lib\distutils\core.py", line 151, in setup
      dist.run_commands()
    File "C:\Users\djordan\Anaconda2\lib\distutils\dist.py", line 953, in run_co
mmands
      self.run_command(cmd)
    File "C:\Users\djordan\Anaconda2\lib\distutils\dist.py", line 972, in run_co
mmand
      cmd_obj.run()
    File "C:\Users\djordan\Anaconda2\lib\site-packages\wheel\bdist_wheel.py", li
ne 179, in run
      self.run_command('build')
    File "C:\Users\djordan\Anaconda2\lib\distutils\cmd.py", line 326, in run_com
mand
      self.distribution.run_command(command)
    File "C:\Users\djordan\Anaconda2\lib\distutils\dist.py", line 972, in run_co
mmand
      cmd_obj.run()
    File "C:\Users\djordan\Anaconda2\lib\distutils\command\build.py", line 127,
in run
      self.run_command(cmd_name)
    File "C:\Users\djordan\Anaconda2\lib\distutils\cmd.py", line 326, in run_com
mand
      self.distribution.run_command(command)
    File "C:\Users\djordan\Anaconda2\lib\distutils\dist.py", line 972, in run_co
mmand
      cmd_obj.run()
    File "versioneer.py", line 1548, in run
      _build_py.run(self)
    File "C:\Users\djordan\Anaconda2\lib\site-packages\setuptools\command\build_
py.py", line 53, in run
      self.build_package_data()
    File "C:\Users\djordan\Anaconda2\lib\site-packages\setuptools\command\build_
py.py", line 118, in build_package_data
      for package, src_dir, build_dir, filenames in self.data_files:
    File "C:\Users\djordan\Anaconda2\lib\site-packages\setuptools\command\build_
py.py", line 66, in __getattr__
      self.data_files = self._get_data_files()
    File "C:\Users\djordan\Anaconda2\lib\site-packages\setuptools\command\build_
py.py", line 83, in _get_data_files
      return list(map(self._get_pkg_data_files, self.packages or ()))
    File "C:\Users\djordan\Anaconda2\lib\site-packages\setuptools\command\build_
py.py", line 95, in _get_pkg_data_files
      for file in self.find_data_files(package, src_dir)
    File "C:\Users\djordan\Anaconda2\lib\site-packages\setuptools\command\build_
py.py", line 114, in find_data_files
      return self.exclude_data_files(package, src_dir, files)
    File "C:\Users\djordan\Anaconda2\lib\site-packages\setuptools\command\build_
py.py", line 198, in exclude_data_files
      files = list(files)
    File "C:\Users\djordan\Anaconda2\lib\site-packages\setuptools\command\build_
py.py", line 234, in <genexpr>
      for pattern in raw_patterns
    File "C:\Users\djordan\Anaconda2\lib\distutils\util.py", line 124, in conver
t_path
      raise ValueError, "path '%s' cannot be absolute" % pathname
  ValueError: path '/' cannot be absolute

  ----------------------------------------
  Failed building wheel for rdtools
  Running setup.py clean for rdtools
Failed to build rdtools
Installing collected packages: rdtools
  Running setup.py install for rdtools ... error
    Complete output from command C:\Users\djordan\Anaconda2\python.exe -u -c "im
port setuptools, tokenize;__file__='c:\\users\\djordan\\appdata\\local\\temp\\1\
\pip-rppf0k-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.
read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" in
stall --record c:\users\djordan\appdata\local\temp\1\pip-7djjkf-record\install-r
ecord.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\rdtools
    copying rdtools\aggregation.py -> build\lib\rdtools
    copying rdtools\clearsky_temperature.py -> build\lib\rdtools
    copying rdtools\degradation.py -> build\lib\rdtools
    copying rdtools\filtering.py -> build\lib\rdtools
    copying rdtools\normalization.py -> build\lib\rdtools
    copying rdtools\_version.py -> build\lib\rdtools
    copying rdtools\__init__.py -> build\lib\rdtools
    running egg_info
    writing requirements to rdtools.egg-info\requires.txt
    writing rdtools.egg-info\PKG-INFO
    writing top-level names to rdtools.egg-info\top_level.txt
    writing dependency_links to rdtools.egg-info\dependency_links.txt
    reading manifest file 'rdtools.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'rdtools.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\djordan\appdata\local\temp\1\pip-rppf0k-build\setup.py", li
ne 88, in <module>
        **setuptools_kwargs)
      File "C:\Users\djordan\Anaconda2\lib\distutils\core.py", line 151, in setu
p
        dist.run_commands()
      File "C:\Users\djordan\Anaconda2\lib\distutils\dist.py", line 953, in run_
commands
        self.run_command(cmd)
      File "C:\Users\djordan\Anaconda2\lib\distutils\dist.py", line 972, in run_
command
        cmd_obj.run()
      File "C:\Users\djordan\Anaconda2\lib\site-packages\setuptools\command\inst
all.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\djordan\Anaconda2\lib\distutils\command\install.py", line 5
63, in run
        self.run_command('build')
      File "C:\Users\djordan\Anaconda2\lib\distutils\cmd.py", line 326, in run_c
ommand
        self.distribution.run_command(command)
      File "C:\Users\djordan\Anaconda2\lib\distutils\dist.py", line 972, in run_
command
        cmd_obj.run()
      File "C:\Users\djordan\Anaconda2\lib\distutils\command\build.py", line 127
, in run
        self.run_command(cmd_name)
      File "C:\Users\djordan\Anaconda2\lib\distutils\cmd.py", line 326, in run_c
ommand
        self.distribution.run_command(command)
      File "C:\Users\djordan\Anaconda2\lib\distutils\dist.py", line 972, in run_
command
        cmd_obj.run()
      File "versioneer.py", line 1548, in run
        _build_py.run(self)
      File "C:\Users\djordan\Anaconda2\lib\site-packages\setuptools\command\buil
d_py.py", line 53, in run
        self.build_package_data()
      File "C:\Users\djordan\Anaconda2\lib\site-packages\setuptools\command\buil
d_py.py", line 118, in build_package_data
        for package, src_dir, build_dir, filenames in self.data_files:
      File "C:\Users\djordan\Anaconda2\lib\site-packages\setuptools\command\buil
d_py.py", line 66, in __getattr__
        self.data_files = self._get_data_files()
      File "C:\Users\djordan\Anaconda2\lib\site-packages\setuptools\command\buil
d_py.py", line 83, in _get_data_files
        return list(map(self._get_pkg_data_files, self.packages or ()))
      File "C:\Users\djordan\Anaconda2\lib\site-packages\setuptools\command\buil
d_py.py", line 95, in _get_pkg_data_files
        for file in self.find_data_files(package, src_dir)
      File "C:\Users\djordan\Anaconda2\lib\site-packages\setuptools\command\buil
d_py.py", line 114, in find_data_files
        return self.exclude_data_files(package, src_dir, files)
      File "C:\Users\djordan\Anaconda2\lib\site-packages\setuptools\command\buil
d_py.py", line 198, in exclude_data_files
        files = list(files)
      File "C:\Users\djordan\Anaconda2\lib\site-packages\setuptools\command\buil
d_py.py", line 234, in <genexpr>
        for pattern in raw_patterns
      File "C:\Users\djordan\Anaconda2\lib\distutils\util.py", line 124, in conv
ert_path
        raise ValueError, "path '%s' cannot be absolute" % pathname
    ValueError: path '/' cannot be absolute

    ----------------------------------------
Command "C:\Users\djordan\Anaconda2\python.exe -u -c "import setuptools, tokeniz
e;__file__='c:\\users\\djordan\\appdata\\local\\temp\\1\\pip-rppf0k-build\\setup
.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '
\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\
djordan\appdata\local\temp\1\pip-7djjkf-record\install-record.txt --single-versi
on-externally-managed --compile" failed with error code 1 in c:\users\djordan\ap
pdata\local\temp\1\pip-rppf0k-build\

**Comment by cdeline** [comment]
[install.log](https://github.com/NREL/rdtools/files/1480608/install.log)
Duplicate behavior on my machine.  I can get around it by using `pip install -e . ` from within the repository.  Here's my installer error log file.

**Comment by cdeline** [comment]
the issue arose between commits SHA-1: cc937b247f370c05579756e4bf4e60ee45837ffc (10/31/17 3:20:53) and SHA-1: b1faba95e7cc78ed15c4ddb68cffb4cf6757a486 (10/31/17 3:29:48) and are likely related to the change in setup.py by adding  `package_data=PACKAGE_DATA`

Confirmed by successfully installing with `package_data=PACKAGE_DATA` commented out.

**Comment by cdeline** [comment]
Fixed in development branch:  changed
PACKAGE_DATA = {
    'rdtools': 'rdtools/data/temperature.hdf5'
}

to

PACKAGE_DATA = {
    'rdtools': ['data/temperature.hdf5']
}

**Comment by mdeceglie** [comment]
fixed in v.1.1.3 release
